### ISSUE TITLE
Xc-fasm2bels is getting error out while running running picoSoC design

### ISSUE THREAD

**Issue by dhruvk-umass** [SymbiFlow/symbiflow-xc-fasm2bels#62]
Hi, i am using picoSoC design for fasm 2 dcp conversion, which using fasm2bels utility i am getting below error,
PROCESS_TILE[tile_type](top.conn, top, tile, tile_features)
KeyError: 'BRKH_INT'

It seems that the process is not defined for BRKH_INT and BRAM_INT_INTERFACE_L tiles in fasm2bels.py, should it be assumed null_process/ process_bram?

**Comment by acomodi** [comment]
Hi @dhruvk-umass. I believe that you are using a FASM file generated directly by VPR.

It is possible that the error is caused by the presence of pseudo PIPs that can be found in the tiles reported by you.

For reference, pseudo PIPs are PIPs that do not configure anything in the fabric.

In general this error is not caught because the conversion from `bit` to `fasm` removes all the pseudo PIPs, but I think that, for completeness, those `BRKH_INT` and `BRAM_INT_INTERFACE_[LR]` should belong to the `null_process` class.

**Comment by dhruvk-umass** [comment]
Yes i have assigned those tiles null_process its working and while using bitstream i not seeing this issue. Thank you .
